sudo: required
services:
- docker
env:
  global:
  - SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_11e130cc9768_key -iv $encrypted_11e130cc9768_iv -in multi-k8s-service-account.json.enc -out multi-k8s-service-account.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file multi-k8s-service-account.json
- gcloud config set project multi-k8s-229912
- gcloud config set compute/zone europe-west2-a
- gcloud container clusters get-credentials multi-k8s-cluster
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t davidainslie/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run davidainslie/react-test npm test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
